controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

movie_show:
    path: /movies/{id}
    controller: App\Controller\HomeController::show

